---
title: "R Notebook"
output: html_notebook
---

# Paper-ready figures

```{r,eval=FALSE}
dys_ileum <- ggarrange(p_il_dys_genus + xlab(""),
          alpha_dys_genus_richness_ileum + xlab("MDI"),
          alpha_dys_genus_shannon_ileum + xlab("MDI"), 
          ncol=3, labels=LETTERS,common.legend = TRUE, legend="right",
          widths =c(0.9,1,1,0.29)) + 
  ggtitle("Terminal ileum")+ 
  theme(plot.title = element_text(hjust=0.5,face = "bold",size = 20))

dys_colon <- ggarrange(p_col_dys_genus + xlab(""),
          alpha_dys_genus_richness_colon + xlab("MDI"),
          alpha_dys_genus_shannon_colon + xlab("MDI"),
          ggplot() + theme_minimal(),
          ncol=4, labels = c("D","E","F",""),
          widths =c(0.9,1,1,0.29), 
          common.legend = TRUE, legend = "none") + 
  ggtitle("Colon") + 
  theme(plot.title = element_text(hjust=0.5,face = "bold",size = 20))

dys_plot <- ggarrange(dys_ileum,dys_colon,nrow=2)

# dys_plot <- ggarrange(p_il_dys_genus + ggtitle("MD-index"),
#           alpha_dys_genus_richness_ileum + ggtitle("Richness"),
#           alpha_dys_genus_shannon_ileum + ggtitle("Shannon"),
#           p_col_dys_genus + ggtitle("MD-index"),
#           alpha_dys_genus_richness_colon + ggtitle("Richness"),
#           alpha_dys_genus_shannon_colon + ggtitle("Shannon"), 
#           common.legend = TRUE, legend = "right", 
#           labels=LETTERS)
```


```{r,eval=FALSE}
pdf("results/clinical/FIGURE6_new.pdf",height = 8,width =12)
dys_plot
dev.off()
```

```{r,eval=FALSE}
variables <- c("Bilirubin",
               "ALP",
               "Fecal.calprotectin",
               "MAYO_PSC",
               "AOM_score", 
               "APRI_score",
               "FIB4_score",
               "Albumin",
               "Platelets",
               "INR",
               "Creatinine",
                     "ALT",
                     "AST",
                     "GGT",
               "Nancy_max",
               "eMAYO",
               "MAYO_dai")
```


```{r, fig.width=5, fig.height=3,eval=FALSE}
boxplots_plots <- list()
corrs <- list()
clinical_plots <- list()

for (clinical_variable in variables){
  
  if (grepl("log_",clinical_variable)) {
   metadata_for_boxplots[,clinical_variable] <- log(as.numeric(metadata_for_boxplots[,gsub("log_","",clinical_variable)]))
   
   metadata_ileum[,clinical_variable] <- log(as.numeric(metadata_ileum[,gsub("log_","",clinical_variable)]))
   metadata_colon[,clinical_variable] <- log(as.numeric(metadata_colon[,gsub("log_","",clinical_variable)]))
  }
  
  # boxplot
  p <- clinical_boxplot(metadata_for_boxplots,
                      variable=clinical_variable)

  boxplots_plots[[clinical_variable]] <- p
  
  # ILEUM
  # correlation
  
  ## ASV
  level="ASV"
  corr <- clinical_correlation(metadata_ileum,clinical_variable,level)
  corrs[[paste0("ileum_asv_",clinical_variable)]] <- corr
  
  p <- clinical_scatter(corr,metadata_ileum,clinical_variable,level)
  clinical_plots[[paste0("ileum_asv_",clinical_variable)]] <- p

  ## Genus
  level="genus"
  corr <- clinical_correlation(metadata_ileum,clinical_variable,level)
  corrs[[paste0("ileum_genus_",clinical_variable)]] <- corr
  
  p <- clinical_scatter(corr,metadata_ileum,clinical_variable,level)
  clinical_plots[[paste0("ileum_genus_",clinical_variable)]] <- p
  
  # correlation
  
  ## ASV
  level="ASV"
  corr <- clinical_correlation(metadata_colon,clinical_variable,level,
                               segment="colon")
  corrs[[paste0("colon_asv_",clinical_variable)]] <- corr
  
  p <- clinical_scatter(corr,metadata_colon,clinical_variable,level)
  clinical_plots[[paste0("colon_asv_",clinical_variable)]] <- p

  ## Genus
  level="genus"
  corr <- clinical_correlation(metadata_colon,clinical_variable,level,
                               segment="colon")
  corrs[[paste0("colon_genus_",clinical_variable)]] <- corr
  
  p <- clinical_scatter(corr,metadata_colon,clinical_variable,level)
  clinical_plots[[paste0("colon_genus_",clinical_variable)]] <- p
}

```

```{r,eval=FALSE}
dys_clinical <- ggarrange(ggplot() + theme_minimal() + 
                            ggtitle("Terminal ileum") + 
                            theme(plot.title = element_text(hjust=0.5,face = "bold",size = 15)),
                          ggplot() + theme_minimal() + 
                            ggtitle("Colon") + 
                            theme(plot.title = element_text(hjust=0.5,face = "bold",size = 15)),
                          clinical_plots$ileum_genus_log_ALP 
                          + xlab("MD-index") 
                          + ggtitle("log_ALP"),
                       clinical_plots$colon_genus_log_ALP +
                         xlab("MD-index") + 
                         ggtitle("log_ALP"),
                       clinical_plots$ileum_genus_log_GGT + 
                         xlab("MD-index") +
                         ggtitle("log_GGT"),
                       clinical_plots$colon_genus_log_GGT + 
                         xlab("MD-index") + 
                         ggtitle("log_GGT"),
                       clinical_plots$ileum_genus_log_APRI_score + 
                          xlab("MD-index") + 
                         ggtitle("log_APRI_score"),
                       clinical_plots$colon_genus_log_APRI_score + 
                          xlab("MD-index") + 
                         ggtitle("log_APRI_score"),
                       clinical_plots$ileum_genus_log_FIB4_score + 
                          xlab("MD-index") + 
                         ggtitle("log_FIB4_score"),
                       clinical_plots$colon_genus_log_FIB4_score + 
                         xlab("MD-index") +
                         ggtitle("log_FIB4_score"),
                       clinical_plots$ileum_genus_log_Albumin +
                         xlab("MD-index") +
                         ggtitle("log_Albumin"),
                       clinical_plots$colon_genus_log_Albumin + 
                         xlab("MD-index") +
                         ggtitle("log_Albumin"),
                       ncol=2,labels=c("","",LETTERS),common.legend = TRUE, legend="right",
                       nrow=6,heights = c(0.1,rep(1,5)))
  #theme(plot.title = element_text(hjust=0.5,face = "bold",size = 20))
```

```{r}
pdf("results/clinical/FIGURE8.pdf",height = 15,width =8)
dys_clinical
dev.off()
```




# Paper-ready figures

## Clinical variables - MD index

```{r}
corrs_ileum <- corrs[grepl("ileum_genus",names(corrs))]
corrs_colon <- corrs[grepl("colon_genus",names(corrs))]
```

### Ileum

```{r}
# Example list structure for demonstration
# Initialize empty lists for r and P values
r_values <- list()
p_values <- list()

names(corrs_ileum) <- gsub("APRI_score","APRI.score",names(corrs_ileum))
names(corrs_ileum) <- gsub("FIB4_score","FIB4.score",names(corrs_ileum))
names(corrs_ileum) <- gsub("MAYO_dai","MAYO.dai",names(corrs_ileum))
names(corrs_ileum) <- gsub("Nancy_max","Nancy.max",names(corrs_ileum))
names(corrs_ileum) <- gsub("MAYO_PSC","MAYO.PSC",names(corrs_ileum))

# Extract bacteria names and clinical variables
for (name in names(corrs_ileum)) {
  clinical_var <- sub("^(.*?_){2}", "",  name)
  bacterium <- "MDI Terminal ileum"
  
  # Fill the r and P lists
  if (!is.null(corrs_ileum[[name]]$r)) {
    r_values[[bacterium]][clinical_var] <- corrs_ileum[[name]]$r
  }
  if (!is.null(corrs_ileum[[name]]$P)) {
    p_values[[bacterium]][clinical_var] <- corrs_ileum[[name]]$P
  }
}

# Convert the lists to data frames
r_df <- do.call(rbind, lapply(r_values, function(x) setNames(as.data.frame(t(x)), names(x))))
p_df <- do.call(rbind, lapply(p_values, function(x) setNames(as.data.frame(t(x)), names(x))))

# Add row names as bacteria names
rownames(r_df) <- names(r_values)
rownames(p_df) <- names(p_values)

colnames(r_df) <- gsub("FIB4.score","FIB-4",colnames(r_df))
colnames(p_df) <- gsub("FIB4.score","FIB-4",colnames(p_df))

colnames(r_df) <- gsub("APRI.score","APRI",colnames(r_df))
colnames(p_df) <- gsub("APRI.score","APRI",colnames(p_df))

colnames(r_df) <- gsub("MAYO.PSC","MAYO PSC",colnames(r_df))
colnames(p_df) <- gsub("MAYO.PSC","MAYO PSC",colnames(p_df))

colnames(r_df) <- gsub("AOM_score","AOM",colnames(r_df))
colnames(p_df) <- gsub("AOM_score","AOM",colnames(p_df))

colnames(r_df) <- gsub("Nancy.max","Nancy max",colnames(r_df))
colnames(p_df) <- gsub("Nancy.max","Nancy max",colnames(p_df))

colnames(r_df) <- gsub("MAYO.dai","MAYO DAI",colnames(r_df))
colnames(p_df) <- gsub("MAYO.dai","MAYO DAI",colnames(p_df))

colnames(r_df) <- gsub("Fecal.calprotectin","Fecal calprotectin",colnames(r_df))
colnames(p_df) <- gsub("Fecal.calprotectin","Fecal calprotectin",colnames(p_df))

pd_df_corrected <- as.data.frame(p.adjust(p_df,method="BH"))
p_df_sig <- pd_df_corrected
p_df_sig[,] <- ""

p_df_sig[pd_df_corrected < 0.05] <- "*"
p_df_sig[pd_df_corrected < 0.01] <- "**"
p_df_sig[pd_df_corrected < 0.001] <- "***"

p_df_sig_ileum <- t(p_df_sig) %>% as.data.frame() %>% `rownames<-`("MDI Terminal ileum")
r_df_ileum <- r_df
```

### Colon

```{r}
# Example list structure for demonstration
# Initialize empty lists for r and P values
r_values <- list()
p_values <- list()

names(corrs_colon) <- gsub("APRI_score","APRI.score",names(corrs_colon))
names(corrs_colon) <- gsub("FIB4_score","FIB4.score",names(corrs_colon))
names(corrs_colon) <- gsub("MAYO_dai","MAYO.dai",names(corrs_colon))
names(corrs_colon) <- gsub("Nancy_max","Nancy.max",names(corrs_colon))
names(corrs_colon) <- gsub("MAYO_PSC","MAYO.PSC",names(corrs_colon))

# Extract bacteria names and clinical variables
for (name in names(corrs_colon)) {
  clinical_var <- sub("^(.*?_){2}", "",  name)
  bacterium <- "MDI Colon"
  
  # Fill the r and P lists
  if (!is.null(corrs_colon[[name]]$r)) {
    r_values[[bacterium]][clinical_var] <- corrs_colon[[name]]$r
  }
  if (!is.null(corrs_colon[[name]]$P)) {
    p_values[[bacterium]][clinical_var] <- corrs_colon[[name]]$P
  }
}

# Convert the lists to data frames
r_df <- do.call(rbind, lapply(r_values, function(x) setNames(as.data.frame(t(x)), names(x))))
p_df <- do.call(rbind, lapply(p_values, function(x) setNames(as.data.frame(t(x)), names(x))))

# Add row names as bacteria names
rownames(r_df) <- names(r_values)
rownames(p_df) <- names(p_values)

colnames(r_df) <- gsub("FIB4.score","FIB-4",colnames(r_df))
colnames(p_df) <- gsub("FIB4.score","FIB-4",colnames(p_df))

colnames(r_df) <- gsub("APRI.score","APRI",colnames(r_df))
colnames(p_df) <- gsub("APRI.score","APRI",colnames(p_df))

colnames(r_df) <- gsub("MAYO.PSC","MAYO PSC",colnames(r_df))
colnames(p_df) <- gsub("MAYO.PSC","MAYO PSC",colnames(p_df))

colnames(r_df) <- gsub("AOM_score","AOM",colnames(r_df))
colnames(p_df) <- gsub("AOM_score","AOM",colnames(p_df))

colnames(r_df) <- gsub("Nancy.max","Nancy max",colnames(r_df))
colnames(p_df) <- gsub("Nancy.max","Nancy max",colnames(p_df))

colnames(r_df) <- gsub("MAYO.dai","MAYO DAI",colnames(r_df))
colnames(p_df) <- gsub("MAYO.dai","MAYO DAI",colnames(p_df))

colnames(r_df) <- gsub("Fecal.calprotectin","Fecal calprotectin",colnames(r_df))
colnames(p_df) <- gsub("Fecal.calprotectin","Fecal calprotectin",colnames(p_df))

pd_df_corrected <- as.data.frame(p.adjust(p_df,method="BH"))
p_df_sig <- pd_df_corrected
p_df_sig[,] <- ""
  
p_df_sig[pd_df_corrected < 0.05] <- "*"
p_df_sig[pd_df_corrected < 0.01] <- "**"
p_df_sig[pd_df_corrected < 0.001] <- "***"

p_df_sig_colon <- t(p_df_sig) %>% as.data.frame() %>% `rownames<-`("MDI Colon")
r_df_colon <- r_df
```

```{r}
p_df_sig <- rbind(p_df_sig_ileum,p_df_sig_colon)
r_df <- rbind(r_df_ileum,r_df_colon)

p_df_sig_mdi <- p_df_sig 
r_df_mdi <- r_df 
```

```{r}
r_df_melt_mdi <- melt(r_df_mdi %>% rownames_to_column("SeqID"))
p_df_melt_mdi <- melt(p_df_sig_mdi %>% rownames_to_column("SeqID"),id.vars = c("SeqID"))

r_df_melt_mdi$SeqID <- factor(r_df_melt_mdi$SeqID,
                              levels=unique(r_df_melt_mdi$SeqID))

p_df_melt_mdi$SeqID <- factor(p_df_melt_mdi$SeqID,
                              levels=unique(p_df_melt_mdi$SeqID))

r_df_melt_mdi$variable <- factor(r_df_melt_mdi$variable,
                                 levels=rev(c("ALP","GGT","ALT","AST","Bilirubin",
                                          "INR","Albumin","Platelets", "Creatinine",
                                          "FIB-4",
                                          "APRI","MAYO PSC","AOM",
                                          "Fecal calprotectin",
                                          "Nancy max", "eMAYO","MAYO DAI")))

p_df_melt_mdi$variable <- factor(p_df_melt_mdi$variable,
                                 levels=rev(c("ALP","GGT","ALT","AST","Bilirubin",
                                          "INR","Albumin","Platelets", "Creatinine",
                                          "FIB-4",
                                          "APRI","MAYO PSC","AOM",
                                          "Fecal calprotectin",
                                          "Nancy max", "eMAYO","MAYO DAI")))
p <- ggplot() + 
  geom_tile(data=r_df_melt_mdi, aes(SeqID, variable, fill= value))  + 
  theme_minimal() + 
  scale_fill_gradient2(name = "Rho", low = "blue", mid = "white", high = "red", midpoint = 0,limits = c(-0.7, 0.7)) + 
  geom_text(data=p_df_melt_mdi,aes(x=SeqID,y=variable,label=value,vjust=0.6)) + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  xlab("") + ylab("")  + 
  ggtitle("MDI")+ 
  theme(plot.title = element_text(hjust=0.5,face = "bold",size = 15))

p
```

## HEATMAP

## Ileum

```{r}
# Example list structure for demonstration
# Initialize empty lists for r and P values
r_values <- list()
p_values <- list()

names(corrs_ileum) <- gsub("APRI_score","APRI.score",names(corrs_ileum))
names(corrs_ileum) <- gsub("FIB4_score","FIB4.score",names(corrs_ileum))
names(corrs_ileum) <- gsub("MAYO_dai","MAYO.dai",names(corrs_ileum))
names(corrs_ileum) <- gsub("Nancy_max","Nancy.max",names(corrs_ileum))
names(corrs_ileum) <- gsub("MAYO_PSC","MAYO.PSC",names(corrs_ileum))

# Extract bacteria names and clinical variables
for (name in names(corrs_ileum)) {
  bacterium <- sub("^(.*?_){3}", "",  name)
  clinical_var <- sub(bacterium,"", sub("^(.*?_){2}", "",  name))
  clinical_var <- gsub("_","",clinical_var)
  
  # Fill the r and P lists
  if (!is.null(corrs_ileum[[name]]$r)) {
    r_values[[bacterium]][clinical_var] <- corrs_ileum[[name]]$r
  }
  if (!is.null(corrs_ileum[[name]]$P)) {
    p_values[[bacterium]][clinical_var] <- corrs_ileum[[name]]$P
  }
}

# Convert the lists to data frames
r_df <- do.call(rbind, lapply(r_values, function(x) setNames(as.data.frame(t(x)), names(x))))
p_df <- do.call(rbind, lapply(p_values, function(x) setNames(as.data.frame(t(x)), names(x))))

# Add row names as bacteria names
rownames(r_df) <- names(r_values)
rownames(p_df) <- names(p_values)

colnames(r_df) <- gsub("APRI.score","APRI",colnames(r_df))
colnames(p_df) <- gsub("APRI.score","APRI",colnames(p_df))

colnames(r_df) <- gsub("FIB4.score","FIB-4",colnames(r_df))
colnames(p_df) <- gsub("FIB4.score","FIB-4",colnames(p_df))


pd_df_corrected <- as.data.frame(apply(p_df,2,function(x) p.adjust(x, method="BH")))
p_df_sig <- pd_df_corrected
p_df_sig[,] <- ""

p_df_sig[pd_df_corrected < 0.05] <- "*"
p_df_sig[pd_df_corrected < 0.01] <- "**"
p_df_sig[pd_df_corrected < 0.001] <- "***"
```


```{r}
r_df_melt <- melt(r_df %>% rownames_to_column("SeqID"))
p_df_melt <- melt(p_df_sig %>% rownames_to_column("SeqID"),id.vars = c("SeqID"))

r_df_melt$variable <- factor(r_df_melt$variable, levels = c("ALP","GGT","Albumin",
                                                            "Platelets","FIB-4",
                                                            "APRI"))
p_df_melt$variable <- factor(p_df_melt$variable, levels = c("ALP","GGT","Albumin",
                                                            "Platelets","FIB-4",
                                                            "APRI"))
r_df_melt$SeqID <- factor(r_df_melt$SeqID, levels = unique(r_df_melt$SeqID))
p_df_melt$SeqID <- factor(p_df_melt$SeqID, levels = unique(p_df_melt$SeqID))

p_ileum <- ggplot() + 
  geom_tile(data=r_df_melt, aes(variable, SeqID, fill= value))  + 
  theme_minimal() + 
  scale_fill_gradient2(name = "Rho", low = "blue", mid = "white", high = "red", midpoint = 0,limits = c(-0.5, 0.5)) + 
  geom_text(data=p_df_melt,aes(x=variable,y=SeqID,label=value,vjust=0.6)) + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  xlab("") + ylab("")  + 
  ggtitle("Terminal ileum")+ 
  theme(plot.title = element_text(hjust=0.5,face = "bold",size = 15))

p_ileum
```

## Colon

```{r}
# Example list structure for demonstration
# Initialize empty lists for r and P values
r_values <- list()
p_values <- list()

names(corrs_colon) <- gsub("APRI_score","APRI.score",names(corrs_colon))
names(corrs_colon) <- gsub("FIB4_score","FIB4.score",names(corrs_colon))
names(corrs_colon) <- gsub("MAYO_dai","MAYO.dai",names(corrs_colon))
names(corrs_colon) <- gsub("Nancy_max","Nancy.max",names(corrs_colon))
names(corrs_colon) <- gsub("MAYO_PSC","MAYO.PSC",names(corrs_colon))


# Extract bacteria names and clinical variables
for (name in names(corrs_colon)) {
  bacterium <- sub("^(.*?_){3}", "",  name)
  clinical_var <- sub(bacterium,"", sub("^(.*?_){2}", "",  name))
  clinical_var <- gsub("_","",clinical_var)
  
  # Fill the r and P lists
  if (!is.null(corrs_colon[[name]]$r)) {
    r_values[[bacterium]][clinical_var] <- corrs_colon[[name]]$r
  }
  if (!is.null(corrs_colon[[name]]$P)) {
    p_values[[bacterium]][clinical_var] <- corrs_colon[[name]]$P
  }
}

# Convert the lists to data frames
r_df <- do.call(rbind, lapply(r_values, function(x) setNames(as.data.frame(t(x)), names(x))))
p_df <- do.call(rbind, lapply(p_values, function(x) setNames(as.data.frame(t(x)), names(x))))

# Add row names as bacteria names
rownames(r_df) <- names(r_values)
rownames(p_df) <- names(p_values)

colnames(r_df) <- gsub("APRI.score","APRI",colnames(r_df))
colnames(p_df) <- gsub("APRI.score","APRI",colnames(p_df))

colnames(r_df) <- gsub("FIB4.score","FIB-4",colnames(r_df))
colnames(p_df) <- gsub("FIB4.score","FIB-4",colnames(p_df))

pd_df_corrected <- as.data.frame(apply(p_df,2,function(x) p.adjust(x, method="BH")))
p_df_sig <- pd_df_corrected
p_df_sig[,] <- ""

p_df_sig[pd_df_corrected < 0.05] <- "*"
p_df_sig[pd_df_corrected < 0.01] <- "**"
p_df_sig[pd_df_corrected < 0.001] <- "***"
```


```{r}
r_df_melt_colon <- melt(r_df %>% rownames_to_column("SeqID"))
p_df_melt_colon <- melt(p_df_sig %>% rownames_to_column("SeqID"),id.vars = c("SeqID"))

r_df_melt_colon$variable <- factor(r_df_melt_colon$variable, levels = c("ALP","GGT","Albumin",
                                                            "Platelets","FIB-4",
                                                            "APRI"))
r_df_melt_colon$variable <- factor(r_df_melt_colon$variable, levels = c("ALP","GGT","Albumin",
                                                            "Platelets","FIB-4",
                                                            "APRI"))

r_df_melt_colon$SeqID <- factor(r_df_melt_colon$SeqID, levels = rev(c(increased,decreased)))
p_df_melt_colon$SeqID <- factor(p_df_melt_colon$SeqID, levels = rev(c(increased,decreased)))

p_colon <- ggplot() + 
  geom_tile(data=r_df_melt_colon, aes(variable, SeqID, fill= value)) + 
  theme_minimal() + 
  scale_fill_gradient2(name = "Rho", low = "blue", mid = "white", high = "red", midpoint = 0,limits = c(-0.5, 0.5)) + 
  geom_text(data=p_df_melt_colon,aes(x=variable,y=SeqID,label=value,vjust=0.6)) + 
  xlab("") + ylab("")  +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  ggtitle("Colon")+ 
  theme(plot.title = element_text(hjust=0.5,face = "bold",size = 15))

p_colon
```

```{r}
p_heatmap <- ggarrange(p_ileum,p_colon,ncol=2,
                       common.legend = TRUE,
                       legend = "right")
```

```{r, eval=FALSE}
pdf("clanok/obrazky/q1/correlation_abundances.pdf",height = 5,width = 10)
p_heatmap
dev.off()
```

```{r}
p_heatmap <- ggarrange(p,p_ileum,p_colon,ncol=3,
                       common.legend = TRUE,
                       widths = c(0.5,1,1),
                       legend = "right")
```

```{r, eval=FALSE}
pdf("clanok/obrazky/q1/correlation_abundances_2.pdf",height = 5,width = 12)
p_heatmap
dev.off()
```